const editor = new JsonEditor("#json-display", {
  order_type: "DEUNA_NOW",
  order: {
    order_id: "kpjh0zVDzfwHVGB8GXmsqVN1PyhuXfhjzQTcBF5",
    store_code: "13006",
    currency: "MXN",
    tax_amount: 0,
    display_tax_amount: "MXN 0.00",
    shipping_amount: 0,
    display_shipping_amount: "MXN 0.00",
    items_total_amount: 8534,
    display_items_total_amount: "MXN 85.34",
    sub_total: 9900,
    display_sub_total: "MXN 99.00",
    total_amount: 14900,
    display_total_amount: "MXN 149.00",
    items: [
      {
        id: "MEDPIZ",
        name: "Original",
        description: "Masa fresca hecha a mano al momento.",
        options: "",
        total_amount: {
          amount: 9900,
          original_amount: 0,
          display_amount: "MXN 99.00",
          display_original_amount: "MXN 0.00",
          currency: "MXN",
          currency_symbol: "$",
          total_discount: 0,
          display_total_discount: "MXN 0.00",
        },
        unit_price: {
          amount: 9900,
          display_amount: "MXN 99.00",
          currency: "MXN",
          currency_symbol: "$",
        },
        tax_amount: {
          amount: 0,
          display_amount: " 0.00",
          currency: "",
          currency_symbol: "",
        },
        quantity: 1,
        uom: "",
        upc: "",
        sku: "",
        isbn: "",
        brand: "",
        manufacturer: "",
        category: "",
        color: "",
        size: "",
        weight: {
          weight: 0,
          unit: "",
        },
        image_url:
          "https://olodominos.blob.core.windows.net/dev/webOptimized/flavors/buildPizza.png",
        details_url: "",
        type: "",
        taxable: false,
        discounts: [],
      },
    ],
    discounts: [
      {
        amount: 50,
        display_amount: "",
        code: "MF99O",
        reference: "",
        description: "Mediana Favorita 1 ing",
        details_url: "",
        free_shipping: {
          is_free_shipping: false,
          maximum_cost_allowed: 0,
        },
        discount_category: "coupon",
        target_type: "",
        type: "",
      },
    ],
    shipping_address: {
      id: 0,
      user_id: "",
      first_name: "Melvin",
      last_name: "Rosales",
      phone: "3222222229",
      identity_document: "",
      lat: 0,
      lng: 0,
      address1: "Piramide del Sol",
      address2: "boom",
      city: "New Mexico",
      zipcode: "31231",
      state_name: "Hola",
      country_code: "MX",
      country: "MX",
      additional_description: "",
      address_type: "other",
      is_default: true,
      created_at: "0001-01-01T00:00:00Z",
      updated_at: "0001-01-01T00:00:00Z",
    },
    shipping_options: {
      type: "delivery",
      details: {
        store_name: "VS001 - 13006",
        address: "Piramide del Sol 1, San Juan Teotihuacan, MX, C.P. 55800",
        address_coordinates: {
          lat: 19.692435,
          lng: -98.843596,
        },
        contact: {
          name: "",
          phone: "5552417171",
        },
        additional_details: {
          pickup_time: "2022-08-08T14:58:20.721Z",
          stock_location: "",
        },
      },
    },
    user_instructions: "",
    status: "pending",
    payment: {
      data: {
        amount: {
          amount: 0,
          currency: "",
        },
        metadata: {},
        from_card: {
          card_brand: "",
          first_six: "",
          last_four: "",
        },
        updated_at: "0001-01-01 00:00:00 +0000 UTC",
        method_type: "",
        merchant: {
          store_code: "",
          id: "",
        },
        created_at: "0001-01-01 00:00:00 +0000 UTC",
        id: "",
        processor: "",
        customer: {
          email: "",
          id: "",
        },
        status: "",
        reason: "",
      },
    },
    gift_card: [],
    redirect_url: "",
    webhook_urls: {
      notify_order: "",
      apply_coupon: "https://railway-nodejs.onrender.com/applyCoupons/{orderId}",
      remove_coupon: "https://railway-nodejs.onrender.com/removeCoupons/{orderId}/code/{couponCode}",
      get_shipping_methods: "https://railway-nodejs.onrender.com/{orderId}",
      update_shipping_method: "https://railway-nodejs.onrender.com/{orderId}/{codeMethod}",
      shipping_rate: "",
      sync_notify_order: ""
    },
    total_discount: 2000,
    display_total_discount: "MXN 0.00",
    shipping: {
      original_amount: 0,
      total_discount: 0,
      discounts: [],
    },
    cash_change: 0,
    shipping_method: {
      code: "pickup",
      name: "",
      min_delivery_date: "",
      max_delivery_date: "",
      cost: 0,
      display_cost: "",
      tax_amount: 0,
      display_tax_amount: "",
      scheduler: [],
    },
    shipping_methods: [
      {
        code: "pickup",
        name: "En mostrador",
        min_delivery_date: "",
        max_delivery_date: "",
        cost: 0,
        display_cost: "",
        tax_amount: 1366,
        display_tax_amount: "",
        scheduler: [],
      },
    ],
  },
});


const payEditor = new JsonEditor("#json-display-pay", {
    order_type: "DEUNA_NOW",
    save_user_info: true,
    transaction_id: "11112222-4a11-4a53-b48c-8c0d8e04a777",
    method_type: "cash",
    order_token: "f2d801b3-4a11-4a53-b48c-8c0d8e04a777",
    amount: 1000,
    email: "aaaa@deuna.com",
    not_sync_payment: true
});
